name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-18.04

    steps:
    - uses: kenchan0130/actions-system-info@master
      id: sys
    - uses: actions/checkout@v2
    - run: mkdir ${{github.workspace}}/bin
    - name: cstrace build prepare
      run: cmake -B ${{github.workspace}}/build -DCMAKE_INSTALL_PREFIX=${{github.workspace}}
      
    - name: cstrace build
      run: cmake --build ${{github.workspace}}/build

    - name: cxbuild build
      uses: JackMcKew/pyinstaller-action-linux@0.1.4
      with: 
        spec: build.spec
    
    - run: chmod +x ${{github.workspace}}/dist/linux/cxbuild
    - run: chmod +x ${{github.workspace}}/bin/cstrace
    - run: cp ${{github.workspace}}/dist/linux/cxbuild ${{github.workspace}}/bin/cxbuild
    - run: tar cvzf Release-cxbuild-${{ steps.sys.outputs.name }}-${{ steps.sys.outputs.release }}.tar.gz bin/cstrace bin/cxbuild
        
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        title: Release cxbuild-${{ github.ref }} for ${{ runner.os }} 
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: latest
        files: Release-cxbuild-${{ steps.sys.outputs.name }}-${{ steps.sys.outputs.release }}.tar.gz

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - run: |
        pip install -r requirements.txt
        pytest tests
